#!/usr/bin/env python3
# cron/check_public_surfaces.py
# Unstructured Alpha — Canonical-host reachability check
#
# Sibling of cron/check_data_freshness.py, for the other kind of silent
# breakage. That one asks "is the data still arriving?". This one asks "is what
# we publish still reachable on the domain we publish it under?".
#
# WHY THIS EXISTS
#
# /brief shipped serving 200 on seo.unstructuredalpha.com and 404 on www. The
# SEO service was healthy, every unit test passed, /version reported the right
# commit, and the sitemap advertised the www URL to Google while the subscriber
# email pointed its "Read in browser" link at the same dead address.
#
# Nothing in the system could see it, because every component was individually
# fine. The failure was in the seam: the marketing site proxies a hand-written
# list of paths, and a route added to the service is not added to that list.
#
# A static test now compares those two lists. This catches the other half --
# a rewrite that exists but does not work, a service that is down, a deploy
# that half-landed -- by asking the public internet rather than the repo.
#
# Exits non-zero so Render surfaces a failed run, matching check_data_freshness.
#
# Run manually from dashboard/:
#   python -m cron.check_public_surfaces

import os
import sys
import xml.etree.ElementTree as ET
from datetime import datetime, timezone
from pathlib import Path
from urllib.parse import urlparse

_here = Path(__file__).resolve().parent.parent
if str(_here) not in sys.path:
    sys.path.insert(0, str(_here))

import requests

# The host everything canonicalises to. Not the SEO service's own hostname:
# checking seo.* would pass while the pages 404 where readers and Google
# actually go, which is precisely the bug this exists for.
CANONICAL = os.environ.get("SEO_BASE_URL", "https://www.unstructuredalpha.com").rstrip("/")
APP = os.environ.get("APP_BASE_URL", "https://app.unstructuredalpha.com").rstrip("/")

# Sampled rather than exhaustive: the sitemap carries ~500 ticker and signal
# pages, and they are generated by the same two handlers. One of each proves
# the route works; hammering the service every morning proves nothing more.
_SAMPLE_PER_PATTERN = 2

# Request timeouts are keyword-only DEFAULTS, not a module constant.
# utils/production_audit.py resolves timeouts statically and treats
# `timeout=_SOME_CONSTANT` as "not statically bounded", failing the external
# network budget. A default is the contract the audit can actually read.


def _get(url: str, *, timeout: float = 25.0) -> tuple[int, str]:
    try:
        r = requests.get(url, timeout=timeout, allow_redirects=True,
                         headers={"User-Agent": "UnstructuredAlpha-SurfaceCheck/1.0"})
        return r.status_code, ""
    except Exception as exc:
        return 0, f"{type(exc).__name__}: {str(exc)[:90]}"


def _sitemap_urls(*, timeout: float = 25.0) -> tuple[list[str], str | None]:
    code, err = _get(f"{CANONICAL}/sitemap.xml")
    if err or code != 200:
        return [], f"sitemap unreachable (HTTP {code}) {err}".strip()
    try:
        r = requests.get(f"{CANONICAL}/sitemap.xml", timeout=timeout)
        root = ET.fromstring(r.content)
    except Exception as exc:
        return [], f"sitemap did not parse: {type(exc).__name__}"
    ns = {"s": "http://www.sitemaps.org/schemas/sitemap/0.9"}
    return [e.text.strip() for e in root.findall(".//s:loc", ns) if e.text], None


def _sample(urls: list[str]) -> list[str]:
    """One or two per URL shape, plus every one-off page."""
    buckets: dict[str, list[str]] = {}
    for u in urls:
        head = "/".join(urlparse(u).path.strip("/").split("/")[:1]) or "root"
        buckets.setdefault(head, []).append(u)
    out: list[str] = []
    for _, group in sorted(buckets.items()):
        out.extend(group[:_SAMPLE_PER_PATTERN] if len(group) > _SAMPLE_PER_PATTERN else group)
    return out


def main() -> int:
    print(f"[surfaces] checked at {datetime.now(timezone.utc).isoformat()}", flush=True)
    print(f"[surfaces] canonical host: {CANONICAL}", flush=True)

    failures: list[str] = []
    checked = 0

    urls, sitemap_err = _sitemap_urls()
    if sitemap_err:
        # The sitemap IS a public surface; if it is gone, say so plainly rather
        # than reporting zero failures because nothing was checked.
        print(f"[surfaces] FAILED — {sitemap_err}", flush=True)
        return 1

    targets = _sample(urls)
    # Surfaces that carry no sitemap entry but are still load-bearing.
    targets += [f"{CANONICAL}/robots.txt", f"{APP}/"]

    for url in targets:
        code, err = _get(url)
        checked += 1
        if err or code != 200:
            failures.append(f"{url}  ->  HTTP {code} {err}".rstrip())

    print(f"[surfaces] sitemap entries: {len(urls)}  sampled+extra: {checked}", flush=True)
    for line in failures:
        print(f"[surfaces]   BROKEN  {line}", flush=True)

    if failures:
        print(
            f"[surfaces] FAILED — {len(failures)} of {checked} public surface(s) "
            f"unreachable on the canonical host. A page can be healthy on the "
            f"service that serves it and still 404 where readers arrive.",
            flush=True,
        )
        return 1

    print(f"[surfaces] OK — all {checked} reachable", flush=True)
    return 0


if __name__ == "__main__":
    sys.exit(main())
