"""A shared link must not render a blank card.

app/layout.tsx pointed og:image and twitter:image at /og-image.png for months
while that file did not exist, so every link posted to X, LinkedIn, Slack or
iMessage previewed as an empty box. Link previews are the cheapest distribution
this product has.

The image is generated by scripts/make_og_image.py and committed. These tests
pin the three things that made it fail silently: the file exists, it is the
size crawlers crop to, and the page still points at that exact filename.
"""

from __future__ import annotations

import struct
from pathlib import Path

DASHBOARD = Path(__file__).resolve().parent.parent
WEB = DASHBOARD / "unstructured-alpha-web" / "app"
OG_IMAGE = DASHBOARD / "unstructured-alpha-web" / "public" / "og-image.png"


def _png_size(path: Path) -> tuple[int, int]:
    """Width and height from the PNG header, without needing Pillow in CI."""
    header = path.read_bytes()[:24]
    assert header[:8] == b"\x89PNG\r\n\x1a\n", "not a PNG"
    return struct.unpack(">II", header[16:24])


def test_the_social_preview_image_exists():
    assert OG_IMAGE.is_file(), (
        "og-image.png is missing, so every shared link previews as a blank card. "
        "Regenerate it with: python scripts/make_og_image.py"
    )


def test_it_is_the_size_crawlers_crop_to():
    assert _png_size(OG_IMAGE) == (1200, 630)


def test_it_is_small_enough_to_fetch_quickly():
    # X drops images over 5MB; a preview is not worth more than a few hundred KB.
    assert OG_IMAGE.stat().st_size < 400_000


def test_the_page_points_at_the_file_that_exists():
    layout = (WEB / "layout.tsx").read_text(encoding="utf-8")
    assert "og-image.png" in layout
    assert "OG_IMAGE" in layout


def test_the_generator_is_committed_so_the_image_can_be_rebuilt():
    script = DASHBOARD / "scripts" / "make_og_image.py"
    assert script.is_file()
    assert "1200" in script.read_text(encoding="utf-8")


def test_the_app_shares_the_same_image():
    """A link to the app previewed with no image at all until 2026-09-20."""
    splash = (DASHBOARD / "scripts" / "inject_boot_splash.py").read_text(encoding="utf-8")
    assert 'META_IMAGE = "https://unstructuredalpha.com/og-image.png"' in splash
    assert 'property="og:image"' in splash

    header = (DASHBOARD / "utils" / "header.py").read_text(encoding="utf-8")
    assert "og-image.png" in header
    assert "summary_large_image" in header, "a card with an image should use the large format"
